name: mentomindtask
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  path_provider: ^2.0.11
  sqflite:
  dio:
  intl:
  bot_toast: ^4.0.3
  flutter_math_fork: ^0.6.3+1
  flutter_widget_from_html: ^0.8.5
  paginable: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

